# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Venuprasad Naik
title: Core Java Developer
email: vpnaik97@gmail.com
website: about.me/venuprasadnaik

# Social links
twitter_username: venuprasad_naik
github_username:  venuprasadnaik
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: venuprasadnaik
linkedin_username: venuprasad
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there, 
  
  I'm Venuprasad a Programmer. I have experience making software and web apps. I have worked at a number of projects gaining teamwork and collaboration skills.

  I am most skilled in: <mark>Core Java</mark> and <mark>Spring Framework</mark>
  


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in programming and software engineering some of my other interests and hobbies are:
   - Badminton
   - Mobile Gaming
   - Cricket
   - Watching F1
   - Conan Show

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
